var networkTypeConfig = {
  "explorerUrl": "",
  "faucetUrl": "http://localhost:100",
  "defaultNetworkType": 104,
  "defaultNodeUrl": "http://myRegularNode.host.com:3000",
  "networkConfigurationDefaults": {
    "maxMosaicDivisibility": 6,
    "namespaceGracePeriodDuration": 2592000,
    "lockedFundsPerAggregate": "10000000",
    "maxCosignatoriesPerAccount": 25,
    "blockGenerationTargetTime": 30,
    "maxNamespaceDepth": 3,
    "maxMosaicDuration": 315360000,
    "minNamespaceDuration": 2592000,
    "maxNamespaceDuration": 157680000,
    "maxTransactionsPerAggregate": 100,
    "maxCosignedAccountsPerAccount": 25,
    "maxMessageSize": 1024,
    "maxMosaicAtomicUnits":  8999999999000000,
    "currencyMosaicId": "6BED913FA20223F8",
    "harvestingMosaicId": "6BED913FA20223F8",
    "defaultDynamicFeeMultiplier": 100,
    "epochAdjustment": 1615853185,
    "totalChainImportance": 7842928625000000,
    "generationHash": "57F7DA205008026C776CB6AED843393F04CD458E0AA2D9F1D5F31A402072B2D6"
  },
  "nodes": [
    {"friendlyName": "myregularnode.host.com", "roles": 2, "url": "http://myRegularNode.host.com:3000"},
    {"friendlyName": "ngl-dual-001.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-001.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-002.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-002.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-003.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-003.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-004.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-004.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-101.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-101.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-102.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-102.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-103.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-103.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-104.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-104.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-201.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-201.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-202.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-202.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-203.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-203.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-204.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-204.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-301.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-301.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-302.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-302.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-303.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-303.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-304.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-304.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-401.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-401.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-402.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-402.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-403.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-403.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-404.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-404.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-501.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-501.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-502.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-502.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-503.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-503.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-504.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-504.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-601.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-601.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-602.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-602.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-603.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-603.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-604.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-604.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-005.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-005.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-006.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-006.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-105.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-105.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-106.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-106.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-205.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-205.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-206.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-206.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-305.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-305.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-306.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-306.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-405.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-405.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-406.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-406.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-505.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-505.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-506.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-506.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-605.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-605.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-dual-606.symbolblockchain.io", "roles": 2, "url": "http://ngl-dual-606.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-api-001.symbolblockchain.io", "roles": 2, "url": "http://ngl-api-001.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-api-301.symbolblockchain.io", "roles": 2, "url": "http://ngl-api-301.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-api-401.symbolblockchain.io", "roles": 2, "url": "http://ngl-api-401.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-api-501.symbolblockchain.io", "roles": 2, "url": "http://ngl-api-501.symbolblockchain.io:3000"},
    {"friendlyName": "ngl-api-601.symbolblockchain.io", "roles": 2, "url": "http://ngl-api-601.symbolblockchain.io:3000"},
  ]
}
var networkConfig = { 104 : networkTypeConfig }
window.networkConfig = networkConfig
console.log('networkConfig loaded!', networkConfig)




