name: alpha
concurrency: production
on: [push]
jobs:
    doc:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: 12.x
              registry-url: https://registry.npmjs.org
          - run: npm ci
          - run: npm run doc
          - name: Deploy Docs 🚀
              uses: JamesIves/github-pages-deploy-action@v4.2.2
              with:
                branch: gh-pages # The branch the action should deploy to.
                folder: ts-docs # The folder the action should deploy.
#        steps:
#            - uses: actions/checkout@v2
#            - run: sudo rm /usr/local/bin/docker-compose
#            - run: curl -L https://github.com/docker/compose/releases/download/${env.DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#            - run: chmod +x docker-compose
#            - sudo mv docker-compose /usr/local/bin
#            - name: Build symbol.yml
#              run: python3 -m catparser --schema symbol/all.cats --include symbol --output  dist/symbol.yml
#            - name: Build nem.yml
#              run: python3 -m catparser --schema nem/all.cats --include nem --output  dist/nem.yml
#            - run: ls -la dist
#            - uses: 'marvinpinto/action-automatic-releases@latest'
#              name: Publish Pre Release
#              if: github.ref == 'refs/heads/main'
#              with:
#                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
#                  automatic_release_tag: 'alpha'
#                  prerelease: true
#                  title: 'Alpha Build'
#                  files: |
#                      dist/symbol.yml
#                      dist/nem.yml
