name: Release
on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Person to greet'
                required: true
                default: 'Mona the Octocat'
            home:
                description: 'location'
                required: false
                default: 'The Octoverse'
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello ${{ github.event.inputs.name }} - in ${{ github.event.inputs.home }}!"
            - name: Checkout code
              uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12.x
                  registry-url: https://registry.npmjs.org
            - run: npm ci
            - run: npm pack
            - run: echo "Release ${{ github.ref }}"
            - id: version
              run: echo "version=$(npm run version --silent)" >> $GITHUB_ENV
            - run: echo "Deploying version ${{ env.version }}"
#              - run: npm publish --tag alpha
#                env:
#                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#            - name: Create Release
#              id: create_release
#              uses: actions/create-release@v1
#              env:
#                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
